baseurl: '/cj-blogs'
# ----------- CONFIGURABLE START -----------
title:            "Scribble with Chiran"
description:      "Such theme, very cool."
url:              https://ichiranjain.github.io/cj-blogs/ # Site url, without a slash at the end.
signoff:          "Chiran" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         When you are pregnant!
    url:          /preg
    external:     false
  - name:         Crypto
    url:          /crypto
    external:     false

defaults:
  - scope:
      path: "_posts/preg"
    values:
      type: "preg"
  - scope:
      path: "_posts/crypto"
    values:
      type: "crypto"
